### ISSUE TITLE
Where is map.menu.create channel definition?

### ISSUE THREAD

**Issue by ssdhaliwal** [CMAPI/cmapi#104]
Reviewing and implementing the map.feature.draw there is a reference to map.menu.create channel - 

menuId = The id of a context menu. If populated, the context menu MUST have already been pre-registered via the map.menu.create channel. If populated, the context menu associated with this id will appear when the feature is 'right-clicked', allowing the user to invoke actions on the feature which will be handled by the widget which originally registered the context menu. If no menuId is assigned, the feature will not have a context menu associated when right-clicked.

**Comment by cbashioum** [comment]
Good question.  Actually - good catch.  This was a leftover from a previous consideration of adding menu support.  We will actually remove menuId in v1.3.  Thanks!!

**Comment by cbashioum** [comment]
Turns out there were references to map.menu.create in multiple places.  We have identified all of them (we think) and removed them.

**Comment by cbashioum** [comment]
Issue addressed in the final version of v1.3.0
