### ISSUE TITLE
fix map.feature.edit.complete and map.feature.edit.update 

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#34]
fix map.feature.edit.complete and map.feature.edit.update because those pages look like they are adding a new channel vice just specifying the details object that is sent on the map.message.complete and map.message.progress channels

**Comment by cbashioum** [comment]
Moved to appropriate places underneath the map.message.progress - still need to add to map.message.complete

**Comment by briscoeej** [comment]
Fixed in RC5
