### ISSUE TITLE
Add value naming convention to spec

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#43]
Add to overview that “In general, values are in lower case or when they are multiple words will be in lower camel case, and when we reference the values in the description we try to use lower case with quotation marks “” and when we are just talking about what the values stand for we use the common formats (e.g., “geojson” in the message, but GeoJSON when referring to the spec).”

And then scrub the spec to make sure we do this

**Comment by briscoeej** [comment]
Addressed in commit 78611c16c43a4f21312ae6577ca6beb426a54b6b
