### ISSUE TITLE
change map.feature.plot.geojson timePrimitive property to array

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#54]
Would it be possible change this property into an array of timespans? This would better support some time based APIs like Cesium.

see https://groups.google.com/forum/?hl=en#!topic/common-map-widget-api/BKDwxpmqStg for more info

**Comment by briscoeej** [comment]
Add as a new optional property "timeSpans" whichh is an array of timeSpan.  This allows for backwards compatibility with anyone who is just using the single timeSpan.

**Comment by briscoeej** [comment]
timeSpans added for 1.3.0 RC7
