### ISSUE TITLE
Add wmsCapabilities property to map.feature.plot.url

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#59]
map.feature.plot.url
Added dimensions property directly to payload of this message.  Format for dimension arrays is defined by WMS spec.  In our telecon we all agreed it would make more sense to add a wmsCapabilities property that contains xml for a valid capabilities document instead.
{
    dimensions: {
        time: {values: […]},
        elevations: {values: […]},
        analysisTime: {values: […]}
    },
    ….
}

**Comment by briscoeej** [comment]
Let's connect with the individual who asked for this and see if they already implemented to identify if critical for 1.3.0

**Comment by cbashioum** [comment]
Editors discussed, and determined that this can be best handled via the following workflow:  Widget sends map.feature.plot.url message to map with wms capabilities object.  The map widget can resolve the URL and display what the widget asked for.  The map widget can then, if so equipped, do a WMS GetCapabilities to allow the user to interact with the WMS server to "nuance" the picture.  This would not be done via CMAPI, but would be direct map widget to WMS server interaction.
