### ISSUE TITLE
Add properties.time to map.view.clicked message

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#60]
map.view.clicked:
When user clicks map we send this notification.  Added same properties.time as for map.status.view.  I would prefer that ‘time’ be an optional top level property though.

**Comment by briscoeej** [comment]
Chris, can you get the original context of request to clarify if the time is the actual physical time user clicked, or if it is related to a timeLine control where the map is viewing data at a specific point in time?

**Comment by briscoeej** [comment]
Added for what will be released as 1.3.0 RC7
