### ISSUE TITLE
Add temporal bounds property to map.status.view 

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#61]
map.status.view:
Currently sent in response to a map.status.request only, but refer to map.view.time below.  Extended this channel by adding properties property that contains temporal bounds (max time, min time, selected time) in a new ‘time’ property:
properties: {
    time: {
        min: 1439931600000,
        max: 1439931800000,
        selected: 1439931700000
    }
}
Values for time properties are milliseconds since UNIX epoch in UTC.
As for map.view.clicked, I would prefer moving time to be an optional top level property of this message.

**Comment by briscoeej** [comment]
This can be added as an optional parameter for 1.3.0

**Comment by briscoeej** [comment]
Added in what will be posted as 1.3.0 RC7
