### ISSUE TITLE
Add map.view.time channel

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#62]
map.view.time:
Sent as a notification of the map’s start, end, or selected time being changed.  This channel name was selected because map.view.clicked was also a notification, but after our telecon it seems like this channel should be eliminated and map.status.view used as the unsolicited notification channel as well as the request/response channel.
{
    min: 1439931600000,
    max: 1439931800000,
    selected: 1439931700000
}

**Comment by briscoeej** [comment]
We will add this as stated in issue #62 as a property appended to the map.status.view message sent out when map view changes
