### ISSUE TITLE
Potentially add map.feature.visibility channel

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#63]
map.feature.visibility:
Notification message sent by map whenever a CMAPI feature (i.e., OpenLayers layer) is shown/hidden.
{fid:<string>, ovlyId:<string>, visible:<bool>}
Based on out telecon, it sounds like you’d prefer to use map.status.visibility for both unsolicited notifications and status request/response.  In that case, this message can be eliminated.

**Comment by briscoeej** [comment]
Need to add documentation to map.overlay and map.feature hide and show that the map SHALL send out the show or hide message if this change was made from the map's UI controls. The MAP SHALL NOT send this message if its change to visibility originates from an external message

**Comment by briscoeej** [comment]
The documentation is updated in what will go out as 1.3.0 RC7
