### ISSUE TITLE
Add map.status.visibility message

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#64]
map.status.visibility:
Sent in response to a map.status.request with visibility as a supplied request type.
{features:[{fid:<string>, ovlyId: <string>, visible:<bool>}]}
Ideally we’d like to support requesting visibility info for a list of features specified as [{fid, ovlyId}].  However, the map.status.request message doesn’t currently support per-request-type parameters.  I had originally wanted to use map.get channel to do this type of request and we discussed it in our telecon.  I believe that may be the way forward.

**Comment by briscoeej** [comment]
This should be covered by map.get
