### ISSUE TITLE
Meaning of range in map.view.zoom

### ISSUE THREAD

**Issue by spyhunter99** [CMAPI/cmapi#69]
documentation says... The distance in meters from the map (note that most 2-D map renderers do not support infinite zoom and the range will be translated into the nearest supported zoom level).

which isn't clear. is this the altitude of the camera/view or the map scale in meters/pixel or something like that?

**Comment by briscoeej** [comment]
This is the distance of the camera to the center of its view.  In a top down view it is the distance between the camera lens and the ground in meters - which is basically the altitude of the camera.  In a 3D map view, it represents the distance to a point at the center of the camera's view, which may not be a point on the ground.

We are using range as it is described at:

https://developers.google.com/kml/documentation/kmlreference#elements-specific-to-lookat

We are updating the text in the CMAPI spec to read:

"The distance in meters from the map.  For a 2D map this may be translated to the closest zoom level.  For a 3D map it should be interpreted as the camera's distance in meters from the center of the map - which is essentially the camera's altitude when looking straight down."
