### ISSUE TITLE
is visible?

### ISSUE THREAD

**Issue by spyhunter99** [CMAPI/cmapi#76]
Should probably consider adding queries to the view service for "is this layer visible" and "is this feature visible?"

this probably needs discussion on whether or not this means, "is not hidden and is within the current map view's bounds"

**Comment by briscoeej** [comment]
The intent of the map.get (we are adding better documentation for this) channel is to be able to perform queries on overlays and features to get status of properties such as visibility.  The visible property indicates a Boolean stat of on / off - not taking into consideration if it is within the geo-spatial view of the current map.

The ability to perform geo-spatial queries in CMAPI is currently out of scope for 1.3.0 but geo queries could created by someone as an extension and considered in future versions.

**Comment by truff** [comment]
There does not appear to be a standardized 'visibility' property on overlays or features.  So this approach will only facilitate interoperability if everyone just happens to use the same property name to mean 'layer is not selected for display in map'.  I also noticed that the documentation for the filter property is lacking.  You have to read the examples to understand that the name/value pairs of a filter object are named 'property' and 'term' and that when multiple filters are supplied in the filters array that they are ANDed together vice ORed.  

This is a capability that my map has via a non-standard channel and I'm interested in doing this the CMAPI way once everything is spec'd out a little better.

**Comment by eric-briscoe** [comment]
@spyhunter99 @truff 
Updates have been made to the map.get documentation to clarify these issues.  the map.get filter attribute now properly documents the use case and have a visible specific portion tot he documentation.  Please take a look online at: http://cmapi.org/versions/v1.3.0/docs/index.html#map.get and let us know if you have any additional feedback to make this better.

**Comment by truff** [comment]
This looks good to me as far as visibility is concerned.  Not sure if there are any other property names that it would be useful to standardize on.

**Comment by spyhunter99** [comment]
thanks Eric
