### ISSUE TITLE
Missing `properties` property in `map.overlay.update`

### ISSUE THREAD

**Issue by alstad** [CMAPI/cmapi#89]
A `map.overlay.create` message can have a `properties` property supporting application specific extensions. `map.overlay.update` does not have this property and it is therefore not possible to update application specific data for a overlay. I suggest to add a `properties` property to `map.overlay.update`.

**Comment by briscoeej** [comment]
Resolved in commit b1d2f666a1500af757f535fd3b75e9d4d605999a on the v1.3.0 branch
