### ISSUE TITLE
Duplicate properties information

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#97]
3) The details property of map.message.complete is given by the child nodes of ToC "Channels & Payloads => map.message => map.message.complete.  In almost all cases it appears that the details object is identical to the channel message that the map.message.complete is responding to.  So why repeat it here?  That just creates the possibility that they accidentally get out of synch.  And that appears to have happened in at least one place.  Compare the two entries for map.overlay.create.  Under the message complete subtree the map.overlay.create includes a menuId while in the original channel message description for that message there is no menuId.

From message https://groups.google.com/forum/?hl=en#!topic/common-map-widget-api/rvq5Wyny9I4

**Comment by eric-briscoe** [comment]
Addressed in RC12 of CMAPI 1.3.0 now online for comment review period of 30 days
