### ISSUE TITLE
Need clarity on when to user map.error vs map.message.complete

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#98]
4) It is not clear when to use map.error vs map.message.complete.  I believe this issue has been raised before, but the spec doesn't appear to have changed.

from message https://groups.google.com/forum/?hl=en#!topic/common-map-widget-api/rvq5Wyny9I4

**Comment by eric-briscoe** [comment]
This is a duplicate of issue #94 Closing
