### ISSUE TITLE
Map.message.complete payloads duplicate with map.message.complete.failures payload

### ISSUE THREAD

**Issue by cbashioum** [CMAPI/cmapi#99]
5) map.message.complete has a failures array which contains objects with a payload property.  The description of that property is "The payload from the original request message that failed to properly execute.".  The way I read the spec that's the exact same thing as the details property in the map.message.complete message.  So if the a map has an error processing a request it appears to me that it is expected to send a map.error and copy the original request message into the map.error.msg property, then, if the request message included a messageId the map should also send a map.message.complete with the original message in the map.message.complete.details property and an array of failure objects, each one containing the original message again in the map.message.complete.failures.failureObject.payload property.

From message https://groups.google.com/forum/?hl=en#!topic/common-map-widget-api/rvq5Wyny9I4

**Comment by eric-briscoe** [comment]
It may be a good idea to mark map.error as deprecated and focus on use of message.complete

**Comment by eric-briscoe** [comment]
Addressed in 1.3.0 RC12 version posted online for 30 comment review period
